### ISSUE TITLE
what's the API key for opencc server?

### ISSUE THREAD

**Issue by prbl** [HenryQW/ttrss_opencc#2]
so we have to 1）set up an opencc server somewhere, 2） change the init.php accordingly, and 3) fill the API key in the preps page ?

**Comment by HenryQW** [comment]
Hi @prbl ,

yes, you can refer to https://github.com/HenryQW/api.henry.wang/blob/master/controllers/openCCController.js. The API key is intended for authencation, it's not required if you don't implement it.

This plugin is still WIP:

1. I'm still solving the issue #1 , so that it can run locally with your ttrss https://github.com/HenryQW/docker-ttrss-plugins
1. I'm still testing its stability under this API server mode, before I deploy a free instance for everyone.

**Comment by HenryQW** [comment]
Please update the plugin and read the latest README.
